# use this to explore the TaleWorlds DLL's from IronPython
# just copy this into a new interactive window

import clr
clr.AddReferenceToFileAndPath(
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.CampaignSystem.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.CampaignSystem.ViewModelCollection.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.Core.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.Core.ViewModelCollection.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.Diamond.AccessProvider.Epic.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.Diamond.AccessProvider.Steam.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.Diamond.AccessProvider.Test.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.Diamond.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.DotNet.AutoGenerated.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.DotNet.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.Engine.AutoGenerated.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.Engine.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.Engine.GauntletUI.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.GauntletUI.Data.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.GauntletUI.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.GauntletUI.ExtraWidgets.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.GauntletUI.PrefabSystem.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.GauntletUI.TooltipExtensions.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.InputSystem.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.Library.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.Localization.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.MountAndBlade.AutoGenerated.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.MountAndBlade.Diamond.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.MountAndBlade.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.MountAndBlade.GauntletUI.Widgets.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.MountAndBlade.Helpers.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.MountAndBlade.ViewModelCollection.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.NavigationSystem.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.Network.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.PlatformService.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.PlatformService.Epic.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.PlatformService.Steam.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.PlayerServices.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.PSAI.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.SaveSystem.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.TwoDimension.dll",
    "..\\..\\..\\bin\\Win64_Shipping_Client\\TaleWorlds.TwoDimension.Standalone.dll"
)

